import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const BRAND_NAME = "Diya Expressions";

export const exportOrdersPdf = (
    orders
) => {
    if (!orders.length) {
        return;
    }

    const doc = new jsPDF();

    const pageWidth =
        doc.internal.pageSize.getWidth();

    const reportDate = new Date().toLocaleString();

    // ===============================
    // Header
    // ===============================

    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageWidth, 30, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);

    doc.text(BRAND_NAME, 14, 16);

    doc.setFontSize(16);

    doc.text(
        "Orders Report",
        pageWidth - 14,
        16,
        {
            align: "right",
        }
    );

    doc.setTextColor(0, 0, 0);

    doc.setFontSize(10);

    doc.text(
        `Generated: ${reportDate}`,
        14,
        38
    );

    // ===============================
    // Summary
    // ===============================

    const totalRevenue = orders.reduce(
        (total, order) =>
            total +
            Number(order.totalPrice || 0),
        0
    );

    doc.setFont(
        "helvetica",
        "bold"
    );

    doc.text(
        `Total Orders: ${orders.length}`,
        14,
        46
    );

    doc.text(
        `Revenue: Rs. ${totalRevenue.toLocaleString()}`,
        14,
        53
    );

    // ===============================
    // Orders Table
    // ===============================

    autoTable(doc, {
        startY: 60,

        head: [
            [
                "Customer",
                "Items",
                "Total",
                "Payment",
                "Status",
                "Order",
            ],
        ],

        body: orders.map((order) => [
            order.user?.name || "-",
            order.orderItems.length,
            `Rs. ${Number(
                order.totalPrice
            ).toLocaleString()}`,
            order.paymentMethod,
            order.paymentStatus,
            order.orderStatus,
        ]),

        styles: {
            fontSize: 9,
            cellPadding: 3,
        },

        headStyles: {
            fillColor: [37, 99, 235],
            textColor: 255,
            fontStyle: "bold",
        },

        alternateRowStyles: {
            fillColor: [245, 247, 250],
        },

        theme: "striped",
    });

    // ===============================
    // Footer
    // ===============================

    const pageHeight =
        doc.internal.pageSize.getHeight();

    doc.setFontSize(10);

    doc.setTextColor(120);

    doc.text(
        `Generated by ${BRAND_NAME} Admin Dashboard`,
        pageWidth / 2,
        pageHeight - 10,
        {
            align: "center",
        }
    );

    const fileDate = new Date()
        .toISOString()
        .slice(0, 10);

    doc.save(
        `Diya-Expressions-Orders-${fileDate}.pdf`
    );
};